obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.04, -0.04], [-0.04, 0.04], [0.04, 0.04], [0.04, -0.04]]
# robot_radius: 0.06


track_unknown_space: true
inflation_radius: 0.01
cost_scaling_factor: 3

map_type: costmap
observation_sources: scan
scan: {sensor_frame: base_scan, data_type: LaserScan, topic: my_mm_robot/laser/scan, marking: true, clearing: true}