global_costmap:
  global_frame: map
  robot_base_frame: link_chassis

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5

  static_map: false
  rolling_window: true
  track_unknown_space: true

  
 
